title: Muhammads Blog
author: Muhammad Muhibullah
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  On this page you will find a collection of my works and collaborations. 

# social links
twitter_username: AlQaim17
github_username:  Muhammad-Muhibullah

show_excerpts: true # set to false to remove excerpts on the homepage
